using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Net.Http.Headers;
using System.Text;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;


namespace YasudaBotFramework
{
    public class BingVideoSearch
    {
        private static string SubscriptionKey = "43e0c893bf2049ed8feaeb67158f4802";

        public static async Task<BingVideoSearchData> VideoSearch(string q, string mkt)
        {

            using (var client = new HttpClient())
            {
                var queryString = HttpUtility.ParseQueryString(string.Empty);

                // Request headers
                client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", SubscriptionKey );

                // Request parameters
                queryString["q"] = q; // "cats";
                queryString["count"] = "5";
                queryString["offset"] = "0";
                queryString["mkt"] = mkt; // "en-us";
                queryString["safeSearch"] = "Moderate";
                var uri = "https://api.cognitive.microsoft.com/bing/v5.0/videos/search?" + queryString;

                HttpResponseMessage msg = await client.GetAsync(uri);
                if (msg.IsSuccessStatusCode)
                {
                    var jsonResponse = await msg.Content.ReadAsStringAsync();
                    var _Data = JsonConvert.DeserializeObject<BingVideoSearchData>(jsonResponse);
                    return _Data;
                }

            }
            return null;
        }

        //public static async Task<YasudaLUIS> ParseUserInput(string strInput)
        //{
        //    string strRet = string.Empty;
        //    string strEscaped = Uri.EscapeDataString(strInput);

        //    using (var client = new HttpClient())
        //    {
        //        string uri = "https://api.projectoxford.ai/luis/v1/application?id=232315bb-e6a8-4de8-8319-c84d1101a6aa&subscription-key=359f741b583d4465a3032d0837e539cb&q=" + strEscaped;
        //        HttpResponseMessage msg = await client.GetAsync(uri);

        //        if (msg.IsSuccessStatusCode)
        //        {
        //            var jsonResponse = await msg.Content.ReadAsStringAsync();
        //            var _Data = JsonConvert.DeserializeObject<YasudaLUIS>(jsonResponse);
        //            return _Data;
        //        }
        //    }
        //    return null;
        //}

    }

    // Generated by Xamasoft JSON Class Generator
    // http://www.xamasoft.com/json-class-generator

        public class Instrumentation
        {
            public string pageLoadPingUrl { get; set; }
        }

        public class Publisher
        {
            public string name { get; set; }
        }

        public class Creator
        {
            public string name { get; set; }
        }

        public class Thumbnail
        {
            public int width { get; set; }
            public int height { get; set; }
        }

        public class Value
        {
            public string name { get; set; }
            public string description { get; set; }
            public string webSearchUrl { get; set; }
            public string thumbnailUrl { get; set; }
            public string datePublished { get; set; }
            public Publisher[] publisher { get; set; }
            public Creator creator { get; set; }
            public string contentUrl { get; set; }
            public string hostPageUrl { get; set; }
            public string encodingFormat { get; set; }
            public string hostPageDisplayUrl { get; set; }
            public int width { get; set; }
            public int height { get; set; }
            public string duration { get; set; }
            public string motionThumbnailUrl { get; set; }
            public string embedHtml { get; set; }
            public bool allowHttpsEmbed { get; set; }
            public int viewCount { get; set; }
            public Thumbnail thumbnail { get; set; }
            public string videoId { get; set; }
            public bool allowMobileEmbed { get; set; }
        }

        public class BingVideoSearchData
        {
            public string _type { get; set; }
            public Instrumentation instrumentation { get; set; }
            public string readLink { get; set; }
            public string webSearchUrl { get; set; }
            public int totalEstimatedMatches { get; set; }
            public Value[] value { get; set; }
            public int nextOffsetAddCount { get; set; }
        }


}